ignores:
  - "@commitlint/*"
  - '@repobuddy/jest'
  - '@semantic-release/*'
  - "@size-limit/*"
  - "@types/jest"
  - jest-*
  - rimraf # https://github.com/depcheck/depcheck/issues/776
  - semantic-release
  - ts-jest
  - tslib
  - typedoc*
